/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int long long int
#endif

extern "C" int calib_predict_function(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
extern "C" int calib_predict_function_alloc_mem(void);
extern "C" int calib_predict_function_init_mem(int mem);
extern "C" void calib_predict_function_free_mem(int mem);
extern "C" int calib_predict_function_checkout(void);
extern "C" void calib_predict_function_release(int mem);
extern "C" void calib_predict_function_incref(void);
extern "C" void calib_predict_function_decref(void);
extern "C" casadi_int calib_predict_function_n_in(void);
extern "C" casadi_int calib_predict_function_n_out(void);
extern "C" casadi_real calib_predict_function_default_in(casadi_int i);
extern "C" const char* calib_predict_function_name_in(casadi_int i);
extern "C" const char* calib_predict_function_name_out(casadi_int i);
extern "C" const casadi_int* calib_predict_function_sparsity_in(casadi_int i);
extern "C" const casadi_int* calib_predict_function_sparsity_out(casadi_int i);
extern "C" int calib_predict_function_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
extern "C" int calib_predict_function_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define calib_predict_function_SZ_ARG 4
#define calib_predict_function_SZ_RES 3
#define calib_predict_function_SZ_IW 0
#define calib_predict_function_SZ_W 0
extern "C" int calib_pose_function(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
extern "C" int calib_pose_function_alloc_mem(void);
extern "C" int calib_pose_function_init_mem(int mem);
extern "C" void calib_pose_function_free_mem(int mem);
extern "C" int calib_pose_function_checkout(void);
extern "C" void calib_pose_function_release(int mem);
extern "C" void calib_pose_function_incref(void);
extern "C" void calib_pose_function_decref(void);
extern "C" casadi_int calib_pose_function_n_in(void);
extern "C" casadi_int calib_pose_function_n_out(void);
extern "C" casadi_real calib_pose_function_default_in(casadi_int i);
extern "C" const char* calib_pose_function_name_in(casadi_int i);
extern "C" const char* calib_pose_function_name_out(casadi_int i);
extern "C" const casadi_int* calib_pose_function_sparsity_in(casadi_int i);
extern "C" const casadi_int* calib_pose_function_sparsity_out(casadi_int i);
extern "C" int calib_pose_function_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
extern "C" int calib_pose_function_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define calib_pose_function_SZ_ARG 1
#define calib_pose_function_SZ_RES 2
#define calib_pose_function_SZ_IW 0
#define calib_pose_function_SZ_W 0
extern "C" int calib_velocity_function(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
extern "C" int calib_velocity_function_alloc_mem(void);
extern "C" int calib_velocity_function_init_mem(int mem);
extern "C" void calib_velocity_function_free_mem(int mem);
extern "C" int calib_velocity_function_checkout(void);
extern "C" void calib_velocity_function_release(int mem);
extern "C" void calib_velocity_function_incref(void);
extern "C" void calib_velocity_function_decref(void);
extern "C" casadi_int calib_velocity_function_n_in(void);
extern "C" casadi_int calib_velocity_function_n_out(void);
extern "C" casadi_real calib_velocity_function_default_in(casadi_int i);
extern "C" const char* calib_velocity_function_name_in(casadi_int i);
extern "C" const char* calib_velocity_function_name_out(casadi_int i);
extern "C" const casadi_int* calib_velocity_function_sparsity_in(casadi_int i);
extern "C" const casadi_int* calib_velocity_function_sparsity_out(casadi_int i);
extern "C" int calib_velocity_function_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
extern "C" int calib_velocity_function_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define calib_velocity_function_SZ_ARG 1
#define calib_velocity_function_SZ_RES 2
#define calib_velocity_function_SZ_IW 0
#define calib_velocity_function_SZ_W 0
extern "C" int calib_point_function(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
extern "C" int calib_point_function_alloc_mem(void);
extern "C" int calib_point_function_init_mem(int mem);
extern "C" void calib_point_function_free_mem(int mem);
extern "C" int calib_point_function_checkout(void);
extern "C" void calib_point_function_release(int mem);
extern "C" void calib_point_function_incref(void);
extern "C" void calib_point_function_decref(void);
extern "C" casadi_int calib_point_function_n_in(void);
extern "C" casadi_int calib_point_function_n_out(void);
extern "C" casadi_real calib_point_function_default_in(casadi_int i);
extern "C" const char* calib_point_function_name_in(casadi_int i);
extern "C" const char* calib_point_function_name_out(casadi_int i);
extern "C" const casadi_int* calib_point_function_sparsity_in(casadi_int i);
extern "C" const casadi_int* calib_point_function_sparsity_out(casadi_int i);
extern "C" int calib_point_function_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
extern "C" int calib_point_function_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define calib_point_function_SZ_ARG 3
#define calib_point_function_SZ_RES 3
#define calib_point_function_SZ_IW 0
#define calib_point_function_SZ_W 0
